### PR TITLE
[WIP] Basic implementation

### PR DESCRIPTION
**Pull request by ericelliott**
Basic implementation based on the working [universal react boilerplate](https://github.com/cloverfield-tools/universal-react-boilerplate).

**Unfinished**

### CODE REVIEW

**Comment by ericelliott** [comment]
@JedWatson @nkbt Want to take a quick look at this PR?

Hoping to consolidate all of the heavy lifting for universal route, render, and Redux hookup from universal-react-boilerplate, Keystone, etc... to this lib.

This is the minimal server implementation. Client should follow soon.

The stuff in `source/test/fixtures` is essentially what users will create. Stuff like their app reducers, routes, redux mappings to react components, i.e. `mapStateToProps()`, etc...

The core API is essentially this:

```js
const wireApp = ({
  React, app
}) => universal({
  React, app, routes, reducers
});
```

On the server, this will augment `app` (which is the Express app) with your route/reducer plumbing. On the client, it'll skip the Express stuff and instead do some added stuff like wire up the browserHistory API.

**Comment by ericelliott** [comment]
The client implementation differs from the server side in a couple important ways:

1. Loads `initialState` from `window.BOOTSTRAP_CLIENT_STATE` (for now -- this should be a configurable option, later).
2. Wires up the history API automatically.

I need to add a route to the client tests so that I can properly test that redux state changes trigger render updates appropriately.

**Comment by nkbt** [comment]
Secret keys are set via ENV vars. They are protected (unless you manually log all env somewhere)

**Comment by ericelliott** [comment]
Yes, I'm aware you can keep keys out of the repo, but who has access to view those environment variables?

**Comment by nkbt** [comment]
Only collaborators as far as I can tell. If I am not a contributor (on gihub), I can't see project settings (and ENVs too of course)

**Comment by ericelliott** [comment]
Travis-CI lets you store encrypted versions, so they're not even available to collaborators, which is preferable I think, because I am pretty liberal with collaborator privileges. =)

**Comment by ericelliott** [comment]
Baseline finished. Time to start adding some necessary configurability, such as passing context in from the server (language, user data, etc...).

**Pull request merged**
